### ISSUE TITLE
Dataset from zillow.com with only 26 rows

### ISSUE THREAD

**Issue by PVN77** [PacktPublishing/Python-Machine-Learning-Blueprints#1]
Hello,
I have tried several times to extract data from zillow.com with import.io extractor, I only got 26 rows.
Here is the urm I put in the extract  :1234: 
http://www.zillow.com/homes/New-York-NY-manhattan_rb/

Despite this, this is a wonderful book .
Thanks for your help
Best regards
Patrick

**Comment by tbranch227** [comment]
Yeah, I think import.io's functionality has changed and you can't handle that piece of chapter 2 the same.  It'd be nice if they had a sample block of data, so you could just skip this piece, if you don't really care.  I'm hoping import.io isn't featured prominently.

**Comment by MurtazaTinwala** [comment]
Hello everyone,

Python Machine Learning Blueprints - Second Edition is out now.
You may find all the updated codes and content in our new edition.

Purchase links to the book:
Amazon - https://www.amazon.com/dp/1788994175
Packt - https://www.packtpub.com/big-data-and-business-intelligence/python-machine-learning-blueprints-second-edition

Regards,
Packt Publishing
