### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by panyuz** [PacktPublishing/Python-Machine-Learning-Blueprints#4]
sudf.loc[:,'Beds'] = sudf['Beds'].map(lambda x: 0 if 'Studio' in x else x)

TypeError: argument of type 'int' is not iterable

**Comment by panyuz** [comment]
```
sudf['Beds']=sudf['Beds'].replace('Studio',0)
```

it is a simple way

**Comment by MurtazaTinwala** [comment]
Hello everyone,

Python Machine Learning Blueprints - Second Edition is out now.
You may find all the updated codes and content in our new edition.

Purchase links to the book:
Amazon - https://www.amazon.com/dp/1788994175
Packt - https://www.packtpub.com/big-data-and-business-intelligence/python-machine-learning-blueprints-second-edition

Regards,
Packt Publishing
