### ISSUE TITLE
In the second chapter, I can't find the nyc.json file. Please tell me how to get this file？

### ISSUE THREAD

**Issue by xiaowenjie21** [PacktPublishing/Python-Machine-Learning-Blueprints#5]
The Build an App to Find Underpriced Apartments chapter , have a nyc.json file, how to get it ?

**Comment by MurtazaTinwala** [comment]
Hello everyone,

Python Machine Learning Blueprints - Second Edition is out now.
You may find all the updated codes and content in our new edition.

Purchase links to the book:
Amazon - https://www.amazon.com/dp/1788994175
Packt - https://www.packtpub.com/big-data-and-business-intelligence/python-machine-learning-blueprints-second-edition

Regards,
Packt Publishing
