### ISSUE TITLE
How could I get the ipo_data.csv data from chapter 4?

### ISSUE THREAD

**Issue by voidguy** [PacktPublishing/Python-Machine-Learning-Blueprints#6]

**Comment by MurtazaTinwala** [comment]
Hello everyone,

Python Machine Learning Blueprints - Second Edition is out now.
You may find all the updated codes and content in our new edition.

Purchase links to the book:
Amazon - https://www.amazon.com/dp/1788994175
Packt - https://www.packtpub.com/big-data-and-business-intelligence/python-machine-learning-blueprints-second-edition

Regards,
Packt Publishing
