### ISSUE TITLE
Can to get the dataset of the book?

### ISSUE THREAD

**Issue by sience999** [PacktPublishing/Python-Machine-Learning-Blueprints#8]
I haved bought the book and it  is a good  book on machine learning.  I am practicing under the instruction, but I encounter a problem. I cann't generate the data needed for the programs, for example I can't get the house price data via import.io in chapter 2, and I can't find the data in website at github. Can anyone supply the data needed for the book to me?  By the way, it seems now the import.io website can't extract data free.

**Comment by MurtazaTinwala** [comment]
Hello everyone,

Python Machine Learning Blueprints - Second Edition is out now.
You may find all the updated codes and content in our new edition.

Purchase links to the book:
Amazon - https://www.amazon.com/dp/1788994175
Packt - https://www.packtpub.com/big-data-and-business-intelligence/python-machine-learning-blueprints-second-edition

Regards,
Packt Publishing
